### ISSUE TITLE
Bug: AP shop items marked sold out

### ISSUE THREAD

**Issue by SquigglyGuy** [jcbantuelle/Archipelago#1]
AP items in all shops will be flagged sold out when one item is purchased from a shop. It also happens if you receive an AP item from a conversation with an NPC. Chests appear to be fine.

Examples:
`Xelpud xmailer.exe Gift (Player2): Twin Statue (Player1)`
Player2's AP shop items can no longer be purchased.

`Yiear Kungfu Shop Item 1 (Player1): Ankh Jewel (Baphomet) (Player2)`
`Yiear Kungfu Shop Item 2 (Player1): Fake Silver Shield (Player1)`
`Yiear Kungfu Shop Item 3 (Player1): Map (Tower of Ruin) (Player2)`
Purchasing shop item 3 will mark shop item 1 and 3 as sold out. Any AP shop items from other shops will also be marked sold out.

`Ankh Jewel (Gate of Guidance) Chest (Player1): Sacred Orb (Player2)`
Collecting the item from the chest sends the item and still allows AP shop items to be purchased.

Edit:
Naked items also appear to work as intended.
`bunplus.com Location (Player1): Sacred Orb (Player2)`
Collecting the item does not mark the shop sold out.

**Comment by jcbantuelle** [comment]
This has been resolved by replacing items for other players with a map, which doesn't have the quantity restriction other items do
