### ISSUE TITLE
Bug: Functionality for items seem to be tied to vanilla chest locations.

### ISSUE THREAD

**Issue by SquigglyGuy** [jcbantuelle/Archipelago#3]
guild.exe plays the jingle for hidden shops after being collected as an AP item. The item is properly sent to the receiving client. The game client that acquired the AP item does not have guild.exe collected and the jingle still plays.

Item collection location:
`Scalesphere Chest (Player2): guild.exe (Player1)`

Edit:
Appears to affect other items as well. Purchasing the AP item version of Twin Statue will give the Twin Statue flag to the client that purchased it.
`Shalom III Shop Item 3 (Player1): Twin Statue (Player2)`
Player1 is able to use the twin gates in Twin Labyrinths.

Other ways of acquiring the item didn't appear to work such as these locations:
`Ankh Jewel (Mausoleum of the Giants) Chest (Player1): Twin Statue (Player1)`
`Rolling Shuriken Location (Player1): Twin Statue (Player2)`
In these two cases neither player were given the flag for the Twin Statue.

Edit 2:
`Modro Shop Item 1 (Player2): Fruit of Eden (Player2)`
The item appears in the host console log and the game client appears to have the item, but the item doesn't function. For this example, the switch at the tree in Eden doesn't appear even though the client shows the Fruit of Eden in inventory.

Edit 3:
Continuing from Edit 2, the flag for items seems to set when doing the check for the vanilla location. Upon opening the Fruit of Eden vanilla chest location, the switch in Eden became active for Player2.

This also happened with the Bronze Mirror chest locations. Player1 and Player2 had not acquired Bronze Mirror, but have completed the Bronze Mirror chest checks. Both clients were able to reveal the backside doors without the Bronze Mirror.

**Comment by jcbantuelle** [comment]
This has been resolved, both for found items and starting items
